token: ""
path:
    - ./../plots/
minerName: UBUNTU_1
apiKey: 728979a0-2f94-4daf-8da2-674dd533d833
cachePath: ""
deviceId: ""
extraParams: { }
log:
    lv: info
    path: ./log/
    name: miner.log
url:
    info: ""
    submit: ""
    line: ""
scanPath: true
scanMinute: 10
debug: ""
language: en

